#
# syntax=docker/dockerfile:1 
#FROM abubakrsidiq/node:latest
# FROM node:latest
FROM alpine

RUN apk add --update npm

#Switching working directory to app
WORKDIR /app

#Copy json files to install dependencies
COPY ["package.json", "package-lock.json", "./"]

#Installing dependencies
RUN npm install --production

#Copying files from locally to image
COPY . .

#Setting environment variables
ENV PORT 5000

#Exposing port to receive request from and respond through
EXPOSE 5000

#Running project
CMD ["node", "api.js"]