name: Card Against Humanity Application Deployment

on: 
  push:
    branches:
      - GitHubAction-Branch

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env: 
      ARM_CLIENT_ID: ${{ secrets.APPID }}
      ARM_CLIENT_SECRET: ${{ secrets.PASSWORD }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
    defaults: 
      run:
        shell: bash
        working-directory: ./VM_Terraform/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -var="SSH_KEY=${{ secrets.SSH_KEY }}" -out test.tfplan

      - name: Terraform Apply
        id: apply
        run: terraform apply test.tfplan

  Ansible and Docker:
    name: "Ansible"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./Ansible_Deploy_Docker/
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Ansible
        id: Ansible
        run: sudo apt update
        run: sudo apt install software-properties-common
        run: sudo apt-add-repository --yes --update ppa:ansible/ansible
        run: sudo apt install ansible
      
      - name: Install Docker
        id: Docker
        run: ansible-playbook -v -i inventory.yml playbook.yml

  






