name: Test Report

on: 
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Dotnet Testing
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '5.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Test with the dotnet CLI
        run: dotnet test --collect:"XPlat Code Coverage" -o "./CAHServicesTest/TestResults"

      - name: corbertura-report
        uses: 5monkeys/cobertura-action@v9
        with:
          path: ./CAHServicesTest/TestResults/*/*.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 70
          skip_covered: false
          show_line: true
          show_branch: true
          show_class_names: true
          show_missing: true
          show_missing: true